spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fecth-registry=false

eureka.server.enable-self-preservation=true
eureka.server.evection-interval-timer-in-ms=5000