spring.application.name=product-service
server.port= 0

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=fernandez77

###################
##CUSTOM SETTINGS##
###################
app.queue.name=log-queue


####################
##Euereka Settings##
####################
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Estas propiedades son para prevenir nombres invalidos del hostame.
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost